regionShortNamesMap:
  "us-east-2": "oh"
  "us-east-1": "va"
  "us-west-1": "ca"
  "us-west-2": "or"
  "ap-east-1": "hk"
  "ap-south-1": "mum"
  "ap-northeast-3": "osa"
  "ap-northeast-2": "sel"
  "ap-southeast-1": "sg"
  "ap-southeast-2": "syd"
  "ap-northeast-1": "ty"
  "ca-central-1": "ca"
  "cn-north-1": "cn"
  "cn-northwest-1": "nx"
  "eu-central-1": "fr"
  "eu-west-1": "irl"
  "eu-west-2": "ldn"
  "eu-west-3": "par"
  "eu-north-1": "sth"
  "me-south-1": "bhr"
  "sa-east-1": "sao"
  "us-gov-east-1": "gce"
  "us-gov-west-1": "gcw"

# The default region to deploy to
awsRegion: us-east-1

# Short region name
# This is used in the namespace to avoid naming collisions to allow deploying the same solution across multiple regions
# Currently using the ISO country code or state code or city abbreviation as short name of the region
# See "regionShortNamesMap" defined above.
# The above mapping needs to be updated when deploying to any region other than the ones listed above in future
awsRegionShortName: ${self:custom.settings.regionShortNamesMap.${self:custom.settings.awsRegion}}

# This prefix is used for naming various resources
namespace: ${self:custom.settings.envName}-${self:custom.settings.awsRegionShortName}-${self:custom.settings.solutionName}

# This is the namespace for naming resources that have global namespace such as S3 bucket names
globalNamespace: ${self:custom.settings.awsAccountInfo.awsAccountId}-${self:custom.settings.namespace}

# Name of the deployment bucket. The serverless framework uploads various artifacts to this bucket.
# These artifacts include things like Lambda function code ZIP files, AWS CloudFormation Templates etc
deploymentBucketName: ${self:custom.settings.globalNamespace}-artifacts

# The S3 bucket name to be used for storing the loan request payload
loansBucketName: ${self:custom.settings.globalNamespace}-loan-requests
loansRequestPrefix: loansdata/requests
loansResponsePrefix: loansdata/responses

# The S3 bucket that hold configuration for circuit breaker configuration
circuitBreakerConfigBucketName: ${self:custom.settings.globalNamespace}-circuit-breaker

# The S3 bucket name to be used for S3 access logging
loggingBucketName: ${self:custom.settings.envName}-${self:custom.settings.solutionName}-logging

# This prefix is used to construct the full name of a table
dbTablePrefix: ${self:custom.settings.namespace}

# Root path in parameter store for parameters used by this solution.
paramStoreRoot: "${self:custom.settings.envName}/${self:custom.settings.solutionName}"

etranUsername: "/${self:custom.settings.paramStoreRoot}/etran/username"
etranPassword: "/${self:custom.settings.paramStoreRoot}/etran/password"
etranSoftwareVendorName: "/${self:custom.settings.paramStoreRoot}/etran/softwareVendorName"
etranHost: https://catweb2.sba.gov
etranRestPath: /rest/elend/flexible/SharedEntryString
# Information about the root data lake admin user.
# The root admin user is created by default in the data lake internal authentication provider
# The root user can be used for provisioning additional authentication providers
# Root user's username
rootUserName: root
# Root user's first name
rootUserFirstName: root
# Root user's last name
rootUserLastName: root

# SQS defaults
# VisibilityTimeout needs to be: (max processing time * 6). Ex: 5 min * 60 * 6 = 1800
queueProcessingVisibilityTimeout: 1800  
# Wait for up to X seconds for messages to arrive
queueProcessingReceiveMessageWaitTimeSeconds: 5 
queueProcessingMessageRetentionPeriod: 1209600 # 14 days
queueProcessingMaxReceiveCount: 5
dlqMessageRetentionPeriod: 1209600 # 14 days